enabled: true
mark:
  texture: INK_SACK:1
  glow: true
  name: "&4Soul&8Binder"
  lore: "&e&oMaybe try placing in a crafting table..."
  text: "&9&o- &4&oSoul&8&oBound"

##
# Allowed and denied items
# ------------------------------------------
# You can use a range of values, eg 1-100
# Also you can use item metadata (durability), eg 351#14
##
allowed:
  - 256-258
  - 267-279
  - 283-286
  - 290-294
  - 298-317
  - 346
denied:
  - 268-271
  - 290