name: MarkItem
version: 0.4
description: Mark your items
authors: [OsipXD, Dereku]

main: ru.endlesscode.markitem.MarkItem

commands:
   markitem:
      description: MarkItem command
      usage: /<command>
      permission: markitem.command